INSERT INTO tracks (title, artist, genre, length)
VALUES
    ("Bohemian Rhapsody", "Queen", "Rock", 354),
    ("Shape of You", "Ed Sheeran", "Pop", 233),
    ("Hotel California", "Eagles", "Rock", 391),
    ("Billie Jean", "Michael Jackson", "Pop", 294),
    ("Imagine", "John Lennon", "Rock", 184),
    ("Rolling in the Deep", "Adele", "Pop", 228),
    ("Sweet Child o' Mine", "Guns N' Roses", "Rock", 355),
    ("Smooth", "Santana ft. Rob Thomas", "Rock-Latino", 276),
    ("Hey Jude", "The Beatles", "Rock", 431),
    ("Shape of My Heart", "Sting", "Pop", 269),
    ("Boogie Wonderland", "Earth, Wind & Fire", "Disco", 252),
    ("Livin' on a Prayer", "Bon Jovi", "Rock", 243),
    ("I Will Always Love You", "Whitney Houston", "Pop", 271),
    ("Smells Like Teen Spirit", "Nirvana", "Rock", 302),
    ("Thriller", "Michael Jackson", "Pop", 358),
    ("Wannabe", "Spice Girls", "Pop", 173),
    ("Back in Black", "AC/DC", "Rock", 255),
    ("Don't Stop Believin'", "Journey", "Rock", 250),
    ("Hello", "Adele", "Pop", 295),
    ("Boys Don't Cry", "The Cure", "Rock", 172),
    ("Like a Prayer", "Madonna", "Pop", 349),
    ("Wonderwall", "Oasis", "Rock", 258),
    ("Crazy", "Gnarls Barkley", "Pop", 181),
    ("Sweet Home Alabama", "Lynyrd Skynyrd", "Rock", 424),
    ("Every Breath You Take", "The Police", "Rock", 251),
    ("I Want to Hold Your Hand", "The Beatles", "Rock", 140),
    ("Uptown Funk", "Mark Ronson ft. Bruno Mars", "Pop", 270),
    ("Dancing Queen", "ABBA", "Pop", 231),
    ("Let It Be", "The Beatles", "Rock", 243),
    ("We Will Rock You", "Queen", "Rock", 122),
    ("Yesterday", "The Beatles", "Rock", 126),
    ("I Wanna Dance with Somebody", "Whitney Houston", "Pop", 288),
    ("Sweet Caroline", "Neil Diamond", "Rock", 201),
    ("Killing Me Softly with His Song", "Roberta Flack", "Pop", 249),
    ("Hey Ya!", "OutKast", "Hip-Hop", 235),
    ("With or Without You", "U2", "Rock", 296),
    ("Billie Jean", "Michael Jackson", "Pop", 293),
    ("Piano Man", "Billy Joel", "Rock", 341),
    ("I Will Survive", "Gloria Gaynor", "Disco", 199),
    ("Angie", "The Rolling Stones", "Rock", 275),
    ("Hey Brother", "Avicii", "Electro", 275),
    ("Girls Just Want to Have Fun", "Cyndi Lauper", "Pop", 218),
    ("Another Brick in the Wall (Part II)", "Pink Floyd", "Rock", 361),
    ("Shape of You", "Ed Sheeran", "Pop", 233),
    ("Wish You Were Here", "Pink Floyd", "Rock", 334),
    ("September", "Earth, Wind & Fire", "Disco", 215),
    ("Drops of Jupiter", "Train", "Rock", 288),
    ("Hallelujah", "Leonard Cohen", "Folk", 295),
    ("Nothing Else Matters", "Metallica", "Metal", 388),
    ("Viva la Vida", "Coldplay", "Rock", 242);